version: "3.9"

volumes:
  auth-data:
  user-data:
  gateway-data:
  finance-data:

services:
  finance-postgres-sql:
    depends_on:
      - kafka
      - gateway-service
    image: postgres:latest
    volumes:
      - finance-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node-hostname == databases

  user-postgres-sql:
    depends_on:
      - kafka
      - gateway-service
    image: postgres:latest
    volumes:
      - user-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node-hostname == databases

  auth-postgres-sql:
    depends_on:
      - kafka
      - gateway-service
    image: postgres:latest
    volumes:
      - auth-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node-hostname == databases

  finance-service:
    depends_on:
      - finance-postgres-sql
      - kafka
      - gateway-service
    build:
      context: ./ov-fma-finance
      args:
        VM_IP: ${VM_IP}
      dockerfile: .dockerfile
    environment:
      - VM_IP=${VM_IP}
    env_file:
      - ./ov-fma-finance/.env
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8083:8080"
    networks:
      - app-network

  auth-service:
    depends_on:
      - auth-postgres-sql
      - kafka
      - gateway-service
    build:
      context: ./ov-fma-auth
      args:
        VM_IP: ${VM_IP}
      dockerfile: .dockerfile
    environment:
      - VM_IP=${VM_IP}
    env_file:
      - ./ov-fma-auth/.env
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8080"
    networks:
      - app-network

  user-service:
    depends_on:
      - user-postgres-sql
      - kafka
      - gateway-service
    build:
      context: ./ov-fma-user
      args:
        VM_IP: ${VM_IP}
      dockerfile: .dockerfile
    environment:
      - VM_IP=${VM_IP}
    env_file:
      - ./ov-fma-user/.env
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    networks:
      - app-network

  gateway-service:
    depends_on:
      - kafka
    build:
      context: ./ov-fma-gateway
      args:
        VM_IP: ${VM_IP}
      dockerfile: .dockerfile
    environment:
      - VM_IP=${VM_IP}
    env_file:
      - ./ov-fma-gateway/.env
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    ports:
      - "9092:9092"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
