server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console-auth
      settings:
        trace: false
        web-allow-others: false

springdoc:
  api-docs:
    path: /v3/api-docs-auth
  swagger-ui:
    path: /swagger-auth

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        servlet:
          DispatcherServlet: DEBUG