server:
  address: 0.0.0.0
  port: 8081

spring:
  kafka:
    auto:
      create:
        topics:
          enable: true
    bootstrap-servers: kafka-1:9092
    producer:
      client-id: "${HOSTNAME}"
#      transaction-id-prefix: "user-service-producer-"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
  redis:
    host: redis-cache
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    io.lettuce.core: TRACE
    io.lettuce: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        servlet:
          DispatcherServlet: DEBUG
        data:
          redis: DEBUG
        cache:
          interceptor: DEBUG