server:
  address: 0.0.0.0
  port: 8083
spring:
  profiles:
    active: prd
  config:
    import: configserver:http://${CONFIG_SERVER_URI}:${CONFIG_SERVER_PORT}
  application:
    name: ov-fma-finance
  cloud:
    bootstrap:
      enabled: true
    config:
      #      uri: http://${CONFIG_SERVER_URI}:${CONFIG_SERVER_PORT}
      failFast: true
      retry:
        initialInterval: 1000
        maxAttempts: 5
        multiplier: 1.5
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}