server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console-finance
      settings:
        trace: false
        web-allow-others: false

springdoc:
  api-docs:
    path: /v3/api-docs-finance
  swagger-ui:
    path: /swagger-finance